tag-names:
  - name: datetime
    type: datetime
    value: '%Y%m%d%H%M'
builds:
  devbase:
    context: /
    dockerfile: Dockerfile.devbase
    pushes:
    - on_tag=joshmahowald/workstationbase:{git_tag}
  awscli:
    context: /
    dockerfile: Dockerfile.awscli
    rewrite_from: devbase
    depends_on: 
    - devbase
    pushes:
      - 'on_tag=joshmahowald/workstation-awscli:{git_tag}'
      - 'on_branch:master=joshmahowald/workstation-awscli:latest'
    labels:
      - 'com.dockermake.git.describe={git_describe}'
  terraform:
    context: /
    dockerfile: Dockerfile.terraform
    rewrite_from: awscli
    depends_on: 
    - awscli
    pushes:
    - 'on_tag=joshmahowald/workstation-aws-terraform:{git_tag}'
    dockerignore:
      - .git
