#Build directory: None
#tag: awscli
FROM joshmahowald/workstationbase:0.2

RUN apk add --update --no-cache python python-dev py-pip \
    && rm -rf /var/cache/apk/* \
    && pip install --upgrade pip \
    && pip install awscli boto boto3 awslogs

RUN curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest 
# TODO add in awless